In [1]:
import pandas as pd 
import numpy as np
import joblib

In [2]:
model = joblib.load(
    r"C:\Users\Khande\Desktop\project 2\Customer-Churn-Prediction\models\random_forest_model.pkl"
)

In [3]:
df = pd.read_csv(
    r"C:\Users\Khande\Desktop\project 2\Customer-Churn-Prediction\data\customer_churn_preprocessed.csv"
)

In [4]:
sample_customer = df.drop("Churn", axis=1).iloc[[0]]

sample_customer

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85

In [5]:
prediction = model.predict(sample_customer)
prediction

array([0])

In [6]:
if prediction[0] == 1:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.

In [7]:
probability = model.predict_proba(sample_customer)
print(probability)

[[0.69 0.31]]

In [8]:
print(f"Probability of Staying : {probability[0][0]:.2f}%")
print(f"Probability of Churning : {probability[0][1]:.2f}%")

Probability of Staying : 0.69%
Probability of Churning : 0.31%

In [9]:
customers = df.drop("Churn", axis=1).head(10)
predictions = model.predict(customers)
predictions

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 0])

In [10]:
results = customers.copy()
results["Prediction"] = predictions
results.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Prediction
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

In [11]:
results["Prediction"] = results["Prediction"].map({0: "Not Churn", 1: "Churn"})
results.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Prediction
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,Not Churn
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,Not Churn
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,Churn
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,Not Churn
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,Churn

In [12]:
results.to_csv(
    r"C:\Users\Khande\Desktop\project 2\Customer-Churn-Prediction\data\customer_predictions.csv",
    index=False
)